### ISSUE TITLE
🔧 Check Docker support for chain upgrades

### ISSUE THREAD

**Issue by mariocao** [sedaprotocol/seda-chain#264]
## 🔧 Chore

Check status of Docker image support for potential future chain upgrades.

Ideally, our docker image should be able to handle chain upgrades seamlessly.
For example, this can be achieved by using `cosmovisor` tool and either having automatic binary downloads or having a Docker volume with the binaries.

This task also includes updating the instructions to run a SEDA node with Docker.

**Comment by hacheigriega** [comment]
I believe the simplest solution would be to copy the upgrade binary into the container. We could add the following instruction to the README or our GitBook:

When an upgrade proposal is passed, node operators are expected to use Cosmovisor to prepare the node for an automatic upgrade. Since the Docker image provided by SEDA is already configured to use Cosmovisor, simply run the following commands to download the upgrade binary and place it in the right location in the container.

```bash
UPGRADE_NAME=v0.0.7 # upgrade name example

wget https://github.com/sedaprotocol/seda-chain/releases/download/$UPGRADE_NAME/sedad-amd64
chmod +x sedad-amd64
docker exec seda_node mkdir -p /home/seda/.sedad/cosmovisor/upgrades/$UPGRADE_NAME/bin
docker cp sedad-amd64 seda_node:/home/seda/.sedad/cosmovisor/upgrades/$UPGRADE_NAME/bin/sedad
```
